/**
 * Zabbix API COM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MethodBase } from './methodBase';


export interface Exception { 
    readonly message?: string | null;
    targetSite?: MethodBase;
    readonly stackTrace?: string | null;
    readonly data?: { [key: string]: object; } | null;
    innerException?: Exception;
    helpLink?: string | null;
    source?: string | null;
    hResult?: number;
}

