/**
 * Zabbix API COM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaskCreationOptions } from './taskCreationOptions';
import { AggregateException } from './aggregateException';
import { TaskStatus } from './taskStatus';


export interface StringTask { 
    readonly result?: string | null;
    readonly id?: number;
    exception?: AggregateException;
    status?: TaskStatus;
    readonly isCanceled?: boolean;
    readonly isCompleted?: boolean;
    readonly isCompletedSuccessfully?: boolean;
    creationOptions?: TaskCreationOptions;
    readonly asyncState?: object | null;
    readonly isFaulted?: boolean;
}

