/**
 * Zabbix API COM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaskStatus = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7;

export const TaskStatus = {
    NUMBER_0: 0 as TaskStatus,
    NUMBER_1: 1 as TaskStatus,
    NUMBER_2: 2 as TaskStatus,
    NUMBER_3: 3 as TaskStatus,
    NUMBER_4: 4 as TaskStatus,
    NUMBER_5: 5 as TaskStatus,
    NUMBER_6: 6 as TaskStatus,
    NUMBER_7: 7 as TaskStatus
};

