/**
 * Zabbix API COM
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaskCreationOptions = 0 | 1 | 2 | 4 | 8 | 16 | 64;

export const TaskCreationOptions = {
    NUMBER_0: 0 as TaskCreationOptions,
    NUMBER_1: 1 as TaskCreationOptions,
    NUMBER_2: 2 as TaskCreationOptions,
    NUMBER_4: 4 as TaskCreationOptions,
    NUMBER_8: 8 as TaskCreationOptions,
    NUMBER_16: 16 as TaskCreationOptions,
    NUMBER_64: 64 as TaskCreationOptions
};

